# Generated by Django 4.2.7 on 2023-12-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogocompleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'catalogocompleto',
            },
        ),
    ]
