# Generated by Django 4.2.7 on 2023-12-06 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appejemplares', '0004_remove_libro_imagen_alter_libro_autor_and_more'),
        ('appusuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField(auto_now_add=True)),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appejemplares.libro')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appusuarios.usuario')),
            ],
            options={
                'verbose_name': 'Datos_Reservas',
            },
        ),
    ]
