# Generated by Django 4.2.7 on 2023-12-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appejemplares', '0003_alter_libro_autor_alter_libro_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=100, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='ubicacion',
            field=models.CharField(max_length=20, verbose_name='Ubicación'),
        ),
    ]
