# Generated by Django 4.2.7 on 2023-12-07 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appejemplares', '0004_remove_libro_imagen_alter_libro_autor_and_more'),
        ('appusuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateTimeField(auto_now=True)),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appejemplares.libro')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appusuarios.usuario')),
            ],
            options={
                'verbose_name': 'Datos_Prestamos',
            },
        ),
    ]
